"""Tests for the public commit metadata check.

Every commit with unwanted metadata is planted at runtime in a temporary repository, so this repository's own history
never contains it. Clean cases must pass; each planted case must be SEEN TO FAIL.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.dirname(HERE))
import commit_metadata_check as cmc  # noqa: E402

CONFIG_PATH = os.path.join(REPO_ROOT, ".tla", "commit_metadata.json")
CONFIG = cmc.load_config(CONFIG_PATH)
NAME = CONFIG["publisher"]["name"]
EMAIL = cmc.publisher_email(CONFIG)
PLATFORM = CONFIG["platform_merge_committers"][0]


class Configuration(unittest.TestCase):
    def test_publisher_email_is_the_github_noreply_form(self):
        self.assertEqual(EMAIL, f"{CONFIG['publisher']['github_user_id']}+{CONFIG['publisher']['github_login']}"
                                "@users.noreply.github.com")

    def test_invalid_configuration_is_refused(self):
        tmp = tempfile.mkdtemp(prefix="commit-metadata-config-")
        self.addCleanup(shutil.rmtree, tmp)
        path = os.path.join(tmp, "bad.json")
        with open(path, "w", encoding="utf-8") as handle:
            json.dump({"schema": "commit-metadata/1", "publisher": {"name": NAME}}, handle)
        with self.assertRaises(ValueError):
            cmc.load_config(path)


class Messages(unittest.TestCase):
    def assert_clean(self, text):
        self.assertEqual(cmc.message_findings(text, CONFIG), [], text)

    def assert_flagged(self, text):
        self.assertTrue(cmc.message_findings(text, CONFIG), text)

    def test_normal_product_messages_pass(self):
        self.assert_clean("Add tenant-isolation implementation and validation harness\n\n"
                          "- retrieval_scope.authorize_and_scope (primary control)\n"
                          "- Real-account verification found an API Gateway authorization inconsistency:\n"
                          "- Tokens are generated by the identity provider.\n")
        self.assert_clean("Merge dual licensing and public release updates\n")

    def test_co_author_trailer_fails(self):
        self.assert_flagged("Add feature\n\nCo-authored-by: Someone <someone@example.org>\n")
        self.assert_flagged("Add feature\n\nCO-AUTHORED-BY: Someone <someone@example.org>\n")

    def test_session_trailer_fails(self):
        self.assert_flagged("Add feature\n\nAgent-Session: https://example.org/sessions/1\n")
        self.assert_flagged("Add feature\n\nTool-Session: abc123\n")

    def test_generated_with_and_generated_by_trailers_fail(self):
        self.assert_flagged("Add feature\n\nGenerated-with: some tool\n")
        self.assert_flagged("Add feature\n\nGenerated-by: some tool\n")
        self.assert_flagged("Add feature\n\nAssisted-by: some tool\n")

    def test_malformed_or_unexpected_attribution_fails(self):
        self.assert_flagged("Add feature\n\nCo-Authored-By Someone <someone@example.org>\n")
        self.assert_flagged("Add feature\n\nCoauthored by someone\n")
        self.assert_flagged("Add feature\n\n\U0001F916 Generated with some tool\n")
        self.assert_flagged("Add feature\n\nGenerated by an assistant\n")


class Identities(unittest.TestCase):
    def test_canonical_commit_passes(self):
        for role in ("author", "committer"):
            self.assertEqual(cmc.identity_findings(role, NAME, EMAIL, False, CONFIG), [])

    def test_unexpected_author_name_fails(self):
        self.assertEqual(cmc.identity_findings("author", "Someone Else", EMAIL, False, CONFIG),
                         ["unexpected author name"])

    def test_unexpected_author_email_fails_without_printing_the_address(self):
        findings = cmc.identity_findings("author", NAME, "someone@example.org", False, CONFIG)
        self.assertEqual(findings, ["unexpected author email (@example.org)"])

    def test_platform_committer_accepted_only_on_merge_commits(self):
        self.assertEqual(cmc.identity_findings("committer", PLATFORM["name"], PLATFORM["email"], True, CONFIG), [])
        self.assertTrue(cmc.identity_findings("committer", PLATFORM["name"], PLATFORM["email"], False, CONFIG))
        self.assertTrue(cmc.identity_findings("author", PLATFORM["name"], PLATFORM["email"], True, CONFIG))

    def test_all_zero_before_commit_checks_the_pushed_commit(self):
        self.assertEqual(cmc.normalise_range("0" * 40 + "..abc"), "abc")
        self.assertEqual(cmc.normalise_range("a..b"), "a..b")


class Repository(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="commit-metadata-repo-")
        self.addCleanup(shutil.rmtree, self.tmp)
        self.git("init", "-q", "-b", "main")

    def git(self, *args, author=(NAME, EMAIL), committer=(NAME, EMAIL)):
        env = dict(os.environ, GIT_CONFIG_GLOBAL=os.devnull, GIT_CONFIG_NOSYSTEM="1",
                   GIT_AUTHOR_NAME=author[0], GIT_AUTHOR_EMAIL=author[1],
                   GIT_COMMITTER_NAME=committer[0], GIT_COMMITTER_EMAIL=committer[1])
        return subprocess.run(["git", "-C", self.tmp, "-c", "commit.gpgsign=false", *args], env=env, check=True,
                              capture_output=True, text=True).stdout.strip()

    def commit(self, message, **identity):
        self.git("commit", "-q", "--allow-empty", "-m", message, **identity)
        return self.git("rev-parse", "HEAD")

    def check(self, revisions="main", pr_text_env=""):
        return cmc.main(["--config", CONFIG_PATH, "--repo", self.tmp, "--range", revisions,
                         "--pr-text-env", pr_text_env])

    def test_canonical_history_with_github_merge_commit_passes(self):
        base = self.commit("Add repository foundation")
        self.git("switch", "-q", "-c", "topic")
        self.commit("Add learner exercise")
        self.git("switch", "-q", "main")
        self.git("merge", "-q", "--no-ff", "-m", "Add learner exercise", "topic",
                 committer=(PLATFORM["name"], PLATFORM["email"]))
        self.assertEqual(self.check("main"), 0)
        self.assertEqual(self.check(f"{base}..main"), 0)

    def test_planted_commits_fail(self):
        base = self.commit("Add repository foundation")
        for message, identity in (
                ("Add feature", {"author": ("Someone Else", EMAIL)}),
                ("Add feature", {"author": (NAME, "someone@example.org")}),
                ("Add feature", {"committer": (PLATFORM["name"], PLATFORM["email"])}),
                ("Add feature\n\nCo-authored-by: Someone <someone@example.org>", {}),
                ("Add feature\n\nAgent-Session: https://example.org/sessions/1", {}),
                ("Add feature\n\nGenerated-with: some tool", {}),
                ("Add feature\n\nGenerated-by: some tool", {})):
            with self.subTest(message=message, identity=identity):
                self.git("reset", "-q", "--hard", base)
                self.commit(message, **identity)
                self.assertEqual(self.check(f"{base}..main"), 1)
                self.assertEqual(self.check("main"), 1)
        self.git("reset", "-q", "--hard", base)
        self.assertEqual(self.check("main"), 0)

    def test_pull_request_text_is_checked_from_the_environment(self):
        self.commit("Add repository foundation")
        os.environ["TEST_PR_TITLE"] = "Add public commit metadata validation"
        os.environ["TEST_PR_BODY"] = "Keeps unexpected commit metadata out of main.\n\nGenerated with some tool\n"
        self.addCleanup(os.environ.pop, "TEST_PR_TITLE", None)
        self.addCleanup(os.environ.pop, "TEST_PR_BODY", None)
        self.assertEqual(self.check("main", "TEST_PR_TITLE"), 0)
        self.assertEqual(self.check("main", "TEST_PR_TITLE,TEST_PR_BODY"), 1)

    def test_unknown_revision_is_a_usage_error(self):
        self.commit("Add repository foundation")
        self.assertEqual(self.check("does-not-exist"), 2)


if __name__ == "__main__":
    unittest.main()
